response = await fetch("https://foundryvtt.com/_api/packages/release_version/", {
  headers: {
    'Content-Type': 'application/json',
    'Authorization': 'fvttp_...'
  },
  method: "POST",
  body: JSON.stringify({
    "id": "example-module",
    "dry-run": true,
    "release": {
      "version": "1.0.0",
      "manifest": "https://github.com/example/example-module/issues/releases/download/release-1.0.0/system.json",
      "notes": "https://github.com/example/example-module/releases/tag/release-1.0.0",
      "compatibility": {
        "minimum": "10.312",
        "verified": "11",
        "maximum": ""
      }
    }
  })
});
response_data = await response.json()
